--------------------------------------------------------
--  Fichier créé - samedi-janvier-02-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CADASTRE
--------------------------------------------------------

  CREATE TABLE "HAITHEM"."CADASTRE" 
   (	"ID_CADASTRE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"SURFACE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPTE
--------------------------------------------------------

  CREATE TABLE "HAITHEM"."COMPTE" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DECAISSEMENT
--------------------------------------------------------

  CREATE TABLE "HAITHEM"."DECAISSEMENT" 
   (	"CODE_DECAISSEMENT" NUMBER, 
	"DATE_DECAISSEMENT" DATE, 
	"MONTANT_DECAISSEMENT" NUMBER(16,3), 
	"METHODE" VARCHAR2(20 BYTE), 
	"ID_EMPLOYE" NUMBER, 
	"REMARQUE_DECAISSEMENT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DECES
--------------------------------------------------------

  CREATE TABLE "HAITHEM"."DECES" 
   (	"CIND" NUMBER, 
	"NOMD" VARCHAR2(20 BYTE), 
	"PRENOMD" VARCHAR2(20 BYTE), 
	"LIEU_DE_NAISSANCED" VARCHAR2(20 BYTE), 
	"NOM_PERED" VARCHAR2(20 BYTE), 
	"PRENOM_PERED" VARCHAR2(20 BYTE), 
	"NOM_DELA_MERED" VARCHAR2(20 BYTE), 
	"PRENOM_DELA_MERED" VARCHAR2(20 BYTE), 
	"NATIONALITED" VARCHAR2(20 BYTE), 
	"SEXED" VARCHAR2(20 BYTE), 
	"IDENTITE_DE_DECLARANTD" VARCHAR2(20 BYTE), 
	"IDENTITE_DE_OFFICIERD" VARCHAR2(20 BYTE), 
	"OBSERVATIONSD" VARCHAR2(500 BYTE), 
	"NOTED" VARCHAR2(200 BYTE), 
	"LIEU_DE_DECES" VARCHAR2(20 BYTE), 
	"DATE_DE_NAISSANCED" DATE, 
	"DATE_DE_DECLARATIONS_DEDECES" DATE, 
	"DATE_DE_DECES" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEMANDES
--------------------------------------------------------

  CREATE TABLE "HAITHEM"."DEMANDES" 
   (	"ID_DEMANDE" NUMBER, 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "HAITHEM"."EMPLOYE" 
   (	"ID" NUMBER, 
	"SALAIRE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_DE_NAISSANCE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENCAISSEMENT
--------------------------------------------------------

  CREATE TABLE "HAITHEM"."ENCAISSEMENT" 
   (	"CODE_ENCAISSEMENT" NUMBER, 
	"DATE_ENCAISSEMENT" DATE, 
	"METHODE_ENCAISSEMENT" VARCHAR2(100 BYTE), 
	"ID_EMPLOYE" NUMBER, 
	"MONTANT_ENCAISSEMENT" NUMBER(16,3), 
	"REMARQUE_ENCAISSEMENT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENT
--------------------------------------------------------

  CREATE TABLE "HAITHEM"."EQUIPEMENT" 
   (	"ID_E" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"REFERENCE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FORMATION
--------------------------------------------------------

  CREATE TABLE "HAITHEM"."FORMATION" 
   (	"IDFORMATION" NUMBER, 
	"IDFORMATEUR" NUMBER, 
	"DATEFORMATION" DATE, 
	"DUREE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NAISSANCE
--------------------------------------------------------

  CREATE TABLE "HAITHEM"."NAISSANCE" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"LIEU_DE_NAISSANCE" VARCHAR2(20 BYTE), 
	"NOM_PERE" VARCHAR2(20 BYTE), 
	"PRENOM_PERE" VARCHAR2(20 BYTE), 
	"NOM_DELA_MERE" VARCHAR2(20 BYTE), 
	"PRENOM_DELA_MERE" VARCHAR2(20 BYTE), 
	"NATIONALITE" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE), 
	"IDENTITE_DE_DECLARANT" VARCHAR2(20 BYTE), 
	"IDENTITE_DE_OFFICIER" VARCHAR2(20 BYTE), 
	"OBSERVATIONS" VARCHAR2(1000 BYTE), 
	"NOTE" VARCHAR2(500 BYTE), 
	"DATE_DE_NAISSANCE" DATE, 
	"DATE_DE_DECLARATION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REC
--------------------------------------------------------

  CREATE TABLE "HAITHEM"."REC" 
   (	"ID" NUMBER, 
	"RAISON" VARCHAR2(50 BYTE), 
	"EMPLACEMENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICULE
--------------------------------------------------------

  CREATE TABLE "HAITHEM"."VEHICULE" 
   (	"ID_V" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"REFERENCE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HAITHEM.CADASTRE
SET DEFINE OFF;
REM INSERTING into HAITHEM.COMPTE
SET DEFINE OFF;
Insert into HAITHEM.COMPTE (USERNAME,PASSWORD) values ('haithem','a');
REM INSERTING into HAITHEM.DECAISSEMENT
SET DEFINE OFF;
Insert into HAITHEM.DECAISSEMENT (CODE_DECAISSEMENT,DATE_DECAISSEMENT,MONTANT_DECAISSEMENT,METHODE,ID_EMPLOYE,REMARQUE_DECAISSEMENT) values ('555',to_date('01/01/21','DD/MM/RR'),'452','cheque','0','well life sucks');
REM INSERTING into HAITHEM.DECES
SET DEFINE OFF;
REM INSERTING into HAITHEM.DEMANDES
SET DEFINE OFF;
REM INSERTING into HAITHEM.EMPLOYE
SET DEFINE OFF;
Insert into HAITHEM.EMPLOYE (ID,SALAIRE,NOM,PRENOM,DATE_DE_NAISSANCE) values ('159','2000','haithem','ghattas',to_date('01/01/00','DD/MM/RR'));
Insert into HAITHEM.EMPLOYE (ID,SALAIRE,NOM,PRENOM,DATE_DE_NAISSANCE) values ('233','0','haithem','zdf',to_date('01/01/00','DD/MM/RR'));
Insert into HAITHEM.EMPLOYE (ID,SALAIRE,NOM,PRENOM,DATE_DE_NAISSANCE) values ('666','2000','ghattassss','haithem',to_date('04/06/20','DD/MM/RR'));
Insert into HAITHEM.EMPLOYE (ID,SALAIRE,NOM,PRENOM,DATE_DE_NAISSANCE) values ('421','5000','rim','asba',to_date('04/06/20','DD/MM/RR'));
Insert into HAITHEM.EMPLOYE (ID,SALAIRE,NOM,PRENOM,DATE_DE_NAISSANCE) values ('0','0',null,null,to_date('01/01/00','DD/MM/RR'));
REM INSERTING into HAITHEM.ENCAISSEMENT
SET DEFINE OFF;
Insert into HAITHEM.ENCAISSEMENT (CODE_ENCAISSEMENT,DATE_ENCAISSEMENT,METHODE_ENCAISSEMENT,ID_EMPLOYE,MONTANT_ENCAISSEMENT,REMARQUE_ENCAISSEMENT) values ('55',to_date('01/01/21','DD/MM/RR'),'methode de payement','0','123','zzzz');
REM INSERTING into HAITHEM.EQUIPEMENT
SET DEFINE OFF;
REM INSERTING into HAITHEM.FORMATION
SET DEFINE OFF;
Insert into HAITHEM.FORMATION (IDFORMATION,IDFORMATEUR,DATEFORMATION,DUREE) values ('555','421',to_date('01/01/00','DD/MM/RR'),'2');
Insert into HAITHEM.FORMATION (IDFORMATION,IDFORMATEUR,DATEFORMATION,DUREE) values ('33','666',to_date('25/06/20','DD/MM/RR'),'1');
Insert into HAITHEM.FORMATION (IDFORMATION,IDFORMATEUR,DATEFORMATION,DUREE) values ('0','159',to_date('01/01/00','DD/MM/RR'),'0');
Insert into HAITHEM.FORMATION (IDFORMATION,IDFORMATEUR,DATEFORMATION,DUREE) values ('159','159',to_date('01/01/00','DD/MM/RR'),'0');
REM INSERTING into HAITHEM.NAISSANCE
SET DEFINE OFF;
Insert into HAITHEM.NAISSANCE (CIN,NOM,PRENOM,LIEU_DE_NAISSANCE,NOM_PERE,PRENOM_PERE,NOM_DELA_MERE,PRENOM_DELA_MERE,NATIONALITE,SEXE,IDENTITE_DE_DECLARANT,IDENTITE_DE_OFFICIER,OBSERVATIONS,NOTE,DATE_DE_NAISSANCE,DATE_DE_DECLARATION) values ('777','sami','moez','tunis','hai','hl','hl','h','hj',null,null,null,null,null,to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'));
Insert into HAITHEM.NAISSANCE (CIN,NOM,PRENOM,LIEU_DE_NAISSANCE,NOM_PERE,PRENOM_PERE,NOM_DELA_MERE,PRENOM_DELA_MERE,NATIONALITE,SEXE,IDENTITE_DE_DECLARANT,IDENTITE_DE_OFFICIER,OBSERVATIONS,NOTE,DATE_DE_NAISSANCE,DATE_DE_DECLARATION) values ('55','haithem','a','tunis','hatel','az','za','za','za','z',null,null,null,null,to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'));
Insert into HAITHEM.NAISSANCE (CIN,NOM,PRENOM,LIEU_DE_NAISSANCE,NOM_PERE,PRENOM_PERE,NOM_DELA_MERE,PRENOM_DELA_MERE,NATIONALITE,SEXE,IDENTITE_DE_DECLARANT,IDENTITE_DE_OFFICIER,OBSERVATIONS,NOTE,DATE_DE_NAISSANCE,DATE_DE_DECLARATION) values ('0',null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'));
REM INSERTING into HAITHEM.REC
SET DEFINE OFF;
Insert into HAITHEM.REC (ID,RAISON,EMPLACEMENT) values ('123','well idk','Sidi Hassine');
Insert into HAITHEM.REC (ID,RAISON,EMPLACEMENT) values ('5','4','Sidi Bou Said');
REM INSERTING into HAITHEM.VEHICULE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index REC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAITHEM"."REC_PK" ON "HAITHEM"."REC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMPTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAITHEM"."COMPTE_PK" ON "HAITHEM"."COMPTE" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FORMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAITHEM"."FORMATION_PK" ON "HAITHEM"."FORMATION" ("IDFORMATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAITHEM"."VEHICULE_PK" ON "HAITHEM"."VEHICULE" ("ID_V") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENCAISSEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAITHEM"."ENCAISSEMENT_PK" ON "HAITHEM"."ENCAISSEMENT" ("CODE_ENCAISSEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NAISSANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAITHEM"."NAISSANCE_PK" ON "HAITHEM"."NAISSANCE" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAITHEM"."EQUIPEMENT_PK" ON "HAITHEM"."EQUIPEMENT" ("ID_E") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DECES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAITHEM"."DECES_PK" ON "HAITHEM"."DECES" ("CIND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DECAISSEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAITHEM"."DECAISSEMENT_PK" ON "HAITHEM"."DECAISSEMENT" ("CODE_DECAISSEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAITHEM"."EMPLOYE_PK" ON "HAITHEM"."EMPLOYE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DECAISSEMENT
--------------------------------------------------------

  ALTER TABLE "HAITHEM"."DECAISSEMENT" ADD CONSTRAINT "DECAISSEMENT_PK" PRIMARY KEY ("CODE_DECAISSEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HAITHEM"."DECAISSEMENT" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
  ALTER TABLE "HAITHEM"."DECAISSEMENT" MODIFY ("METHODE" NOT NULL ENABLE);
  ALTER TABLE "HAITHEM"."DECAISSEMENT" MODIFY ("MONTANT_DECAISSEMENT" NOT NULL ENABLE);
  ALTER TABLE "HAITHEM"."DECAISSEMENT" MODIFY ("DATE_DECAISSEMENT" NOT NULL ENABLE);
  ALTER TABLE "HAITHEM"."DECAISSEMENT" MODIFY ("CODE_DECAISSEMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPTE
--------------------------------------------------------

  ALTER TABLE "HAITHEM"."COMPTE" ADD CONSTRAINT "COMPTE_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HAITHEM"."COMPTE" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HAITHEM"."COMPTE" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEHICULE
--------------------------------------------------------

  ALTER TABLE "HAITHEM"."VEHICULE" MODIFY ("ID_V" NOT NULL ENABLE);
  ALTER TABLE "HAITHEM"."VEHICULE" ADD CONSTRAINT "VEHICULE_PK" PRIMARY KEY ("ID_V")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "HAITHEM"."EQUIPEMENT" MODIFY ("ID_E" NOT NULL ENABLE);
  ALTER TABLE "HAITHEM"."EQUIPEMENT" ADD CONSTRAINT "EQUIPEMENT_PK" PRIMARY KEY ("ID_E")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORMATION
--------------------------------------------------------

  ALTER TABLE "HAITHEM"."FORMATION" ADD CONSTRAINT "FORMATION_PK" PRIMARY KEY ("IDFORMATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HAITHEM"."FORMATION" MODIFY ("IDFORMATEUR" NOT NULL ENABLE);
  ALTER TABLE "HAITHEM"."FORMATION" MODIFY ("IDFORMATION" NOT NULL ENABLE);
  ALTER TABLE "HAITHEM"."FORMATION" MODIFY ("DATEFORMATION" NOT NULL ENABLE);
  ALTER TABLE "HAITHEM"."FORMATION" MODIFY ("DUREE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DECES
--------------------------------------------------------

  ALTER TABLE "HAITHEM"."DECES" MODIFY ("CIND" NOT NULL ENABLE);
  ALTER TABLE "HAITHEM"."DECES" ADD CONSTRAINT "DECES_PK" PRIMARY KEY ("CIND")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENCAISSEMENT
--------------------------------------------------------

  ALTER TABLE "HAITHEM"."ENCAISSEMENT" ADD CONSTRAINT "ENCAISSEMENT_PK" PRIMARY KEY ("CODE_ENCAISSEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HAITHEM"."ENCAISSEMENT" MODIFY ("CODE_ENCAISSEMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEMANDES
--------------------------------------------------------

  ALTER TABLE "HAITHEM"."DEMANDES" MODIFY ("ID_DEMANDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NAISSANCE
--------------------------------------------------------

  ALTER TABLE "HAITHEM"."NAISSANCE" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "HAITHEM"."NAISSANCE" ADD CONSTRAINT "NAISSANCE_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REC
--------------------------------------------------------

  ALTER TABLE "HAITHEM"."REC" ADD CONSTRAINT "REC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HAITHEM"."REC" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "HAITHEM"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HAITHEM"."EMPLOYE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FORMATION
--------------------------------------------------------

  ALTER TABLE "HAITHEM"."FORMATION" ADD CONSTRAINT "IDF" FOREIGN KEY ("IDFORMATEUR")
	  REFERENCES "HAITHEM"."EMPLOYE" ("ID") ENABLE;
